### ISSUE TITLE
"cross-lingual word similarity score average" is nan

### ISSUE THREAD

**Issue by 02agarwalt** [ccsasuke/umwe#1]
*moved over from email correspondence*

Having an issue when trying to map fastText-provided "fr" and "tl" source embeddings to target "en" with the following command:

python unsupervised.py --dis_most_frequent 50000 --src_langs fr tl --tgt_lang en

Everything runs (and ends) smoothly, but the "cross-lingual word similarity score average" is always "nan" after every iteration. I've tried with several different language combinations and I never see a value. The train log is attached.
[train.log](https://github.com/ccsasuke/umwe/files/2405980/train.log)

**Comment by 02agarwalt** [comment]
The precisions for tl-en are always 0, for some reason. I used the get_evaluation.sh script and it populated the evaluation dictionaries, including fr-en and tl-en.

**Comment by ccsasuke** [comment]
Hi,

Thank you for moving the issue to GitHub.

The NaN issue is indeed expected. The reason is that neither fr-en or tl-en has SEMEVAL cross-lingual wordsim evaluation data, and the average was computed over 0 language pairs. 
I can fix the code so that it does not display the NaN message in this case, but the code works fine in its current form and there is no need to worry about the NaN issue.

On the other hand, for TL always having 0 word translation precision, the problem might be deeper.
The original Facebook MUSE embeddings are known to fail on certain language pairs (https://aclanthology.info/papers/P18-1072/p18-1072, https://aclanthology.info/papers/P18-1073/p18-1073)
Our method is a multilingual generalization of MUSE, which performs better than MUSE but would probably also fail on those language pairs.
Sometimes, one can get the training to converge by training multiple times (with different random seeds), but for some language pairs, it seems the purely unsupervised method is just not robust enough.
I would suggest you to train the original bilingual MUSE embedding on TL-EN and see if that gives non-zero precision. If it does, please let me know and I will investigate further.

**Comment by 02agarwalt** [comment]
That makes sense. MUSE is indeed failing on TL-EN as well. Does this mean that some language combinations can only be trained using the supervised method? And if so, is there a general rule of thumb one can use to identify these languages (monolingual vec size, etc.)?

**Comment by ccsasuke** [comment]
Hi,

If the unsupervised method fails consistently (e.g. no success after 5 or 10 runs with different seeds), you can also try training with the "identical char supervision", which could arguably also count as "unsupervised" since it does not require human annotations.

As of how to identify these languages, I believe it is still a open question. The papers I referred to in the previous response posed some hypotheses, though. For instance, Søgaard et al. said: "unsupervised bilingual dictionary induction performs much worse on morphologically rich languages that are not dependent marking"

**Comment by 02agarwalt** [comment]
Got it. Thanks for all the help!

**Comment by ccsasuke** [comment]
You are welcome!
